### ISSUE TITLE
Could not resolve host: api.tradestatistics.io

### ISSUE THREAD

**Issue by istrazivac** [ropensci/tradestatistics#56]
Dear All,

I'm trying to use "tradestatistics" to pull data but, after successful installation, I keep getting an error: "Error in open.connection(con, "rb") :Could not resolve host: api.tradestatistics.io".
The code is simple: ots_create_tidy_data(years = 2002, reporters = "chl", partners = "chn")

I'm fairly new to R, but I would say that this error message means that either the server is down, or I've connectivity issues. I was trying to access it from three different computers with various security (firewall and antivirus softwares) but I keep getting the same error.

Does anyone else have the same issue?

Thank you!

**Comment by pachadotdev** [comment]
>  Hi @istrazivac 

So sorry! I was able to look at this today
The issue is that a student tried to mine bitcoins in the server, and the server was immediately shut down as a part of acceptable uses
I've just deployed everything again, and the package is working on my side. In a few minutes the automated tests should be completed
